### ISSUE TITLE
Enable Hot Module Replacement

### ISSUE THREAD

**Issue by Toilal** [skatejs/generator-skatejs#8]
Any plan to support Hot Module Reload inside this generator ? Do you have any resource about this for skatejs ?

**Comment by alexlafroscia** [comment]
Current plans? No. Interested? Sure!

I don't know very much about Webpack, or what would be required to make that work, but if you can get it working I would love to set that up!

**Comment by Toilal** [comment]
I'm quite new to webpack too, but i've played with HMR with VueJS. Vue provides an API to reload components (https://github.com/vuejs/vue-hot-reload-api) , so the idea is to create a webpack loader that adds at compile time the hot module reload code just after the component source code. 

Do you know if skateJS provides any entrypoint for reloading a component ?

**Comment by alexlafroscia** [comment]
I don't think it does right now (I'm pretty new to Skate.js at the moment and in the process of getting more familiar with the source code).

I'd recommend opening an issue on Skate and linking back to this issue; I'm happy to support it on my end if there _is_ an API that I can use.

**Comment by Toilal** [comment]
Here's an issue talking about HMR : https://github.com/skatejs/skatejs/issues/564

**Comment by Toilal** [comment]
It seems trying to create a component with the same name as previous one should Hot Reload...

**Comment by alexlafroscia** [comment]
Okay, awesome. I'll investigate at some point, but this is lower on my priority list right now. I'd love to make it work though, so I'll get to it eventually!

**Comment by Toilal** [comment]
Yes no problem, i'll try to help too when I have some free time for this, thanks !

**Comment by alexlafroscia** [comment]
Since I've replaced the original "demo" concept with [Storybook](https://storybook.js.org/), I'm going to close this.
